package com.example.portside;

public class Affirmations {
    public static final String[] AFFIRMATIONS = {
            "You didn’t just win—you rewrote the rulebook. 🏆",
            "Success looks suspiciously good on you 😎",
            "You crushed it like a soda can at a monster truck rally 🚛",
            "Achievement unlocked: Legend status 🕹️✨",
            "You make excellence look easy. Rude. 👏",
            "If winning were a sport, you'd go pro 🥇",
            "That goal didn’t stand a chance against you 💥",
            "You turned effort into epic. Nicely done! 🚀",
            "Is there anything you *can’t* conquer? 👑",
            "You nailed it so hard the hammer retired 🔨😂",
            "That was smoother than fresh peanut butter 🥜",
            "You didn’t rise to the occasion—you elevated it 📈",
            "Mission accomplished with style points 🎯",
            "You’re basically a walking victory parade 🎉",
            "That success fits you perfectly 👌",
            "You brought, you saw, you absolutely dominated 💪",
            "Even gravity can’t keep you down 🌍⬆️",
            "You made that challenge regret existing 😅",
            "Gold medal energy all day 🥇✨",
            "You’re the plot twist success stories dream of 📖",
            "That was chef’s kiss perfection 👨‍🍳💋",
            "You just upgraded from impressive to iconic 🌟",
            "Your determination deserves its own fan club 🎺",
            "You did that like it owed you money 💰",
            "Some call it luck. I call it skill 😌",
            "You outperformed expectations and physics 🚀",
            "That was a masterclass in winning 🎓",
            "You handled that like a seasoned superhero 🦸",
            "Success called—it wants your autograph ✍️",
            "You just turned effort into fireworks 🎆",
            "You make hustle look glamorous 💼✨",
            "That wasn’t a win. That was a statement 📢",
            "You smashed it like a piñata at a party 🎊",
            "Your grind just paid dividends 💸",
            "Achievement suits you better than pajamas 😄",
            "You’ve got champion vibes for days 🏆",
            "That goal waved a white flag 🏳️",
            "You climbed that mountain in style 🏔️",
            "You’re allergic to mediocrity 🤧",
            "You turned pressure into diamonds 💎",
            "That was bold, brilliant, and beautifully done 👏",
            "You’re basically excellence in human form 🤖✨",
            "You just set the bar higher. Again. 📏",
            "Winning follows you like a loyal puppy 🐶",
            "You executed that flawlessly 🎯",
            "You made the impossible file a complaint 😂",
            "That was smoother than jazz on a Sunday 🎷",
            "You’re proof hard work has great taste 😌",
            "You just flexed on reality 💪",
            "That performance deserves a standing ovation 👏",
            "You didn’t just try—you triumphed 🥳",
            "You’re the reason goals believe in themselves 🌟",
            "That was next-level brilliance 🧠✨",
            "You made excellence your side hustle 💼",
            "You’re cooking with premium ambition 🔥",
            "You aced it like it was an open-book test 📚",
            "You put the ‘pro’ in progress 🏅",
            "You just made success look effortless 😏",
            "That challenge blinked first 👀",
            "You turned grit into glory 🏆",
            "You are what happens when focus wins 🎯",
            "You handled that like a boss… the final boss 🎮",
            "You’re running on premium determination ⛽",
            "You made that milestone sparkle ✨",
            "That was cleaner than a brand-new notebook 📓",
            "You’ve got unstoppable main-character energy 🎬",
            "You didn’t fold—you flourished 🌸",
            "You’re basically a success magnet 🧲",
            "That was elite-level execution 🏹",
            "You just rewrote your own limits 📜",
            "You conquered that like royalty 👑",
            "You turned ambition into applause 👏",
            "You made that hurdle look decorative 🏃",
            "You didn’t sweat—you sparkled ✨",
            "You’ve got victory in your DNA 🧬",
            "That was textbook excellence 📘",
            "You just made history jealous 📚",
            "You’re a one-person hype squad 📣",
            "That was smoother than fresh ice ⛸️",
            "You climbed higher than expectations 📈",
            "You brought thunder to a drizzle 🌩️",
            "You’ve mastered the art of winning 🎨",
            "That goal never saw you coming 😄",
            "You make progress look poetic 🖋️",
            "You didn’t hesitate—you dominated 💥",
            "You’re powered by pure determination 🔋",
            "That success has your fingerprints all over it 🖐️",
            "You turned effort into applause 👏",
            "You just unlocked beast mode 🐯",
            "You handled that like a seasoned legend 🏆",
            "You’re out here collecting victories like souvenirs 🧳",
            "That was crisp, clean, and clutch 🧼",
            "You turned the grind into gold 🥇",
            "You just made greatness look casual 😌",
            "You conquered that with flair 🎩",
            "You’re living proof that hard work wins 💼",
            "That was a power move if I’ve ever seen one ♟️",
            "You didn’t just succeed—you soared 🦅",
            "Are you a magician? Because that win was pure sorcery. 🪄",
            "You're the human equivalent of a double rainbow. 🌈🌈",
            "I'm reporting you for being too good at life. 🚩",
            "Your success is my favorite plot twist. 📖✨",
            "Save some talent for the rest of us mortals! 🤏",
            "You're officially the main character now. 🎭",
            "That was so smooth it’s legally classified as butter. 🧈",
            "Did it hurt when you fell from the top of the leaderboard? 😇",
            "You’re like a software update that actually works. 💻✅",
            "I’d let you lead my heist team any day. 🏦💰",
            "Your brain deserves its own star on the Walk of Fame. ⭐️",
            "Is there anything you can't do? Asking for a friend. 🤔",
            "You just made that look easier than eating pizza. 🍕",
            "Your vibe is currently set to 'Absolute Legend'. 📈",
            "NASA called; they want their rocket scientist back. 🚀",
            "You’re the 'pro' in 'procrastination'... wait, no. Just 'pro'! 🏆",
            "If cool was a crime, you’d be serving a life sentence. ⚖️",
            "You win at life. Everyone else can go home now. 🏠",
            "I’m officially starting your fan club. Membership is $0. 🚩",
            "You have the confidence of a Kanye West song. 🎤",
            "You’re the cherry on top of a very successful sundae. 🍒",
            "Is your middle name 'Victory'? Because it should be. 📛",
            "You’re like a microwave—fast, efficient, and hot. 🔥",
            "You just won the internet. Please collect your prize. 🌐",
            "I bet you don’t even have to try, you just 'are'. 💅",
            "You’re the MVP of basically everything right now. 🏅",
            "Your aura is glowing so bright I need sunglasses. 😎",
            "Can I hire you to just walk around and be impressive? 💼",
            "You’re the reason they have to make new trophies. 🏆",
            "If you were a vegetable, you'd be a 'cute-cumber'. 🥒",
            "I'm 100% convinced you're a cyborg from the future. 🤖",
            "You make excellence look like a casual hobby. 🎨",
            "Your win rate is making the statistics look fake. 📊",
            "You’re the gold standard of being awesome. 🔱",
            "That performance was a total 'chef's kiss'. 🤌👨‍🍳"
    };
}
